### ISSUE TITLE
Problem when trying to load a sound via LoadSoundFromWave

### ISSUE THREAD

**Issue by VitalZero** [raysan5/rres#13]
When using rres to load a Wave (compressed, uncompressed and without any encryption), there's an access violation error at runtime when LoadSoundFromWave() is called **when I use it on my game**. (Edit) the error is presented when using "LoadSoundFromWave" and I use a wave filled with rres valid data.
When I try to reproduce the problem on another "program", the sound is being loaded, but ends abruptly around 3/4 of the time before the sound ends.
The Wave struct seems to be filled ok with rres data, the strange thing is, that if rres fails to load the data and then the Sound is filled with that empty Wave, there's no error and the app executes normally but without that sound obviously.

This is the code I used: (note that this worked with Texture2D and Fonts using Image)
```cpp
#include "raylib.h"

#define RRES_IMPLEMENTATION
#include "rres.h"

#define RRES_RAYLIB_IMPLEMENTATION
#define RRES_SUPPORT_COMPRESSION_LZ4
#include "rres-raylib.h"
#include <cstdint>

int main()
{
	InitWindow(800, 600, "rres test");
	InitAudioDevice();

	Texture2D texture = {};
	Sound sound = {};

	rresCentralDir dir = rresLoadCentralDirectory("assets.rres");

	uint32_t id = rresGetResourceId(dir, "destroyed.ogg");
	uint32_t id1 = rresGetResourceId(dir, "final1.png");

	rresResourceChunk chunk = rresLoadResourceChunk("assets.rres", id);
	rresResourceChunk chunk1 = rresLoadResourceChunk("assets.rres", id1);

	int result = UnpackResourceChunk(&chunk);

	if (result == RRES_SUCCESS)
	{
		Image image = LoadImageFromResource(chunk1);
		texture = LoadTextureFromImage(image);
		UnloadImage(image);
	}

	Wave wave = LoadWaveFromResource(chunk);
	sound = LoadSoundFromWave(wave);
	UnloadWave(wave);

	rresUnloadResourceChunk(chunk);
	rresUnloadCentralDirectory(dir);

	PlaySound(sound);

	while (!WindowShouldClose())
	{
		BeginDrawing();
		ClearBackground(BLACK);

		DrawText("Raylib", 20, 20, 30, RAYWHITE);

		DrawTexture(texture, 20, 50, RAYWHITE);
		EndDrawing();
	}

	UnloadTexture(texture);
	UnloadSound(sound);
	CloseAudioDevice();
	CloseWindow();

	return 0;
}
```
This is the output from the console:
![imagen](https://user-images.githubusercontent.com/46072303/190515739-4a1a5279-a754-4364-ba9f-6a5e2219c7af.png)

and this is the video of it (video from discord channel):
[https://discord.com/channels/426912293134270465/685498858393829376/1020091517265788999](url)

Using c++ 17 with MSVS

Notes:
- Loading a wave directly from the file, then loading the sound from that wave, doesnt give any problems.
- the assets file "called assets.rres" was made on the web version of rres, it wasaround 5 MB worth of files (mostly sound, a couple of png and some text files)
- Didn't used SetCipherPassword and UnpackResourceChunk because the file is neither compressed or encrypted, and gives the same error if I use them anyways.

I hope it helps!
Greetings!

**Comment by VitalZero** [comment]
Sorry!, forgot to add the rres file.
here it is:  [rres file](https://drive.google.com/file/d/1aDpZYiW72xNcT7ktBbBVSxnkarRUhMnf/view?usp=sharingl)

**Comment by VitalZero** [comment]
Issue doesn't happen with mono channel wave files.

**Comment by raysan5** [comment]
@VitalZero Actually, it should neither happen with multi-channel audio data... I keep it open for further review.

**Comment by VitalZero** [comment]
@raysan5 ok, no problem. Thank you!. Sorry! :D

**Comment by BeardedBread** [comment]
Hi @raysan5 . I think I managed to recreate the issue:
1. Generate a ~2.3 seconds WAV file, in both stereo and mono format with the same parameters in rFX, and then separately create the rres files using the online rrespacker, with *no encryption and compression*: [wavecheck.zip](https://github.com/raysan5/rres/files/12908377/wavecheck.zip)
2. A test program is used load the wave file from the rres file and the original wave file.
```c
#include "raylib.h"

#define RRES_IMPLEMENTATION
#include "rres.h"

#define RRES_RAYLIB_IMPLEMENTATION
#define RRES_SUPPORT_COMPRESSION_LZ4
#include "rres-raylib.h"

#include <stdio.h>

// Modify FILE_NAME for testing
#define FILE_NAME "test" 
#define RRES_FILE FILE_NAME ".rres"
#define WAV_FILE FILE_NAME ".wav"

int main(void)
{
    InitWindow(800, 600, "raylib");
    InitAudioDevice();
    SetTargetFPS(60);

    // Rres load
    Sound sound = {0};
    rresCentralDir dir = rresLoadCentralDirectory(RRES_FILE);
    uint32_t id = rresGetResourceId(dir, WAV_FILE);
    rresResourceChunk chunk = rresLoadResourceChunk(RRES_FILE, id);
    Wave wave = LoadWaveFromResource(chunk);
    printf("%d %d %d %d\n", wave.frameCount, wave.sampleRate, wave.sampleSize, wave.channels);
    sound = LoadSoundFromWave(wave);
    UnloadWave(wave);

    // Direct load
    Sound originalSound = {0};
    wave = LoadWave(WAV_FILE);
    printf("%d %d %d %d\n", wave.frameCount, wave.sampleRate, wave.sampleSize, wave.channels);
    originalSound = LoadSoundFromWave(wave);
    UnloadWave(wave);

    while (!WindowShouldClose())
    {

        if (IsKeyReleased(KEY_P)) PlaySound(sound);
        if (IsKeyReleased(KEY_O)) PlaySound(originalSound);

        BeginDrawing();
            ClearBackground(BLACK);
            DrawText("Wave Test", 20, 20, 30, RAYWHITE);
        EndDrawing();
    }

    UnloadSound(sound);
    UnloadSound(originalSound);
    CloseAudioDevice();
    CloseWindow();
}
```

Result:
    - Mono version: both versions are okay
    - Stereo version: the one from rres repeats itself, while the original wave file plays normally.

The issue should be here:
https://github.com/raysan5/rres/blob/64e09624052243fc06678db8cb38282d4a6a4c31/src/rres-raylib.h#L276
The calculation didn't account the number of channels. So the change would be:
```c
unsigned int size = wave.frameCount*wave.sampleSize*wave.channels/8;
```

After making this change, I've also check against the raw data size, which is calculated with:
```c
// WAVE has 4 properties + a count, so 5 unsigned int.
unsigned int raw_size = chunk.info.baseSize - 5 * sizeof(unsigned int);
```
Both matches up, and the issue seems to be resolved.

I've tested this on Linux Mint 21.2, with raylib 4.5. Could I get a verification on this on another platform?  
If all okay, I can open a PR for this.

**Comment by Bigfoot71** [comment]
I have the same problem, and I've also noticed that depending on the arrangement of the rres file _(made with rrespacker)_, the audio glitches at the end of playback are not the same each time.

I confirm, however, that there is no issue with mono sounds.
