### ISSUE TITLE
RRES-RAYLIB.H is missing the extern "C defines

### ISSUE THREAD

**Issue by VitalZero** [raysan5/rres#15]
Hello!!
rres-raylib.h is missing the cplusplus if defined stuff:

before the functions:

```c
#if defined(__cplusplus)
extern "C" {            // Prevents name mangling of functions
#endif
```
and at the end of the functions (after #endif // RRES_RAYLIB_IMPLEMENTATION)
```c
#if defined(__cplusplus)
}
#endif
```
 with this added, rres can be compiled without any issue on c++, including it on a separated .c file using the rres headers and its implementations. It compiles, and it works.

Results:
![image](https://user-images.githubusercontent.com/46072303/210496353-8058ec8f-0359-4af3-b587-88c7d1209b7d.png)

**Comment by raysan5** [comment]
Reviewed!

**Comment by VitalZero** [comment]
thx!!
