### ISSUE TITLE
[rrem] Segmentation Fault on folder dropping onto it

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/rres#4]
as title, drop a folder onto it and instead of (ideally) adding folder contents and also creating a hiarchy

it would be nice to have a "path" inside the resource pack like so...

/textures/level1/foo.png
/textures/level2/foo.png  // same name different media
/textures/level2/bar.png

**Comment by chriscamacho** [comment]
or are you intending that there should be level1 and level2 packs instead ?

**Comment by raysan5** [comment]
@chriscamacho this project is not ready yet, still under development!
