### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by PerMalmberg** [raysan5/rres#7]
Hi,

The README.md file states `rRES file-format is licensed under zlib/libpng license`, but the LICENSE file contains the MIT-license.

Br,

Per

**Comment by raysan5** [comment]
Thanks @PerMalmberg, reviewed in commit https://github.com/raysan5/rres/commit/d7028e786b56835bbf06c81b2d2a3e3abd0008a7.

Please note that this project is a work-in-progress, `rres` design could suffer some modification and `rrem` tool is not functional yet. :)
